# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gpumetropolis, .registration = TRUE
NULL

#' Evaluate the batched Gaussian-mean log-density kernel.
#'
#' Internal helper that exposes the compute kernel in isolation so it can be
#' checked directly. `candidates` holds one mean proposal per chain; the return
#' value holds one log-density per chain.
#' @noRd
rust_log_density_batch <- function(candidates, data, sigma) .Call(wrap__rust_log_density_batch, candidates, data, sigma)

#' Run the batched random-walk Metropolis sampler (CPU reference).
#'
#' Internal worker behind the R function `metropolis_gaussian_mean()`. Returns
#' a list with the `n_iter` by `n_chains` matrix of draws and the per-chain
#' acceptance rate.
#' @noRd
rust_metropolis_gaussian_mean <- function(data, sigma, n_iter, init, proposal_sd, seed) .Call(wrap__rust_metropolis_gaussian_mean, data, sigma, n_iter, init, proposal_sd, seed)

#' Evaluate the batched Gaussian-mean log-density through the CubeCL kernel.
#'
#' Internal helper. `backend` selects the compute runtime: "cpu" or "cuda".
#' Used to check that the CubeCL path is wired into the package build.
#' @noRd
rust_gaussian_logdens_gpu <- function(candidates, data, sigma, backend) .Call(wrap__rust_gaussian_logdens_gpu, candidates, data, sigma, backend)

#' Evaluate a compiled log-likelihood bytecode program over all chains.
#'
#' Internal worker behind the generic API. `code` holds opcode/arg pairs,
#' `params` holds `n_chains * n_params` values grouped by chain. Returns one
#' log-likelihood sum per chain.
#' @noRd
rust_loglik_sum <- function(code, consts, n_params, data, n_cols, n_obs, params, n_chains, backend) .Call(wrap__rust_loglik_sum, code, consts, n_params, data, n_cols, n_obs, params, n_chains, backend)

#' Run the generic batched Metropolis sampler over a compiled model.
#'
#' Internal worker behind `gpu_metropolis()`. The log-density is given as
#' compiled bytecode; `draws` is returned flat in the column-major order of an
#' R array of dimension (n_iter, n_chains, n_params).
#' @noRd
rust_gpu_metropolis <- function(loglik_code, loglik_consts, n_params, data, n_cols, n_obs, prior_code, prior_consts, init, proposal_sd, n_iter, seed, backend) .Call(wrap__rust_gpu_metropolis, loglik_code, loglik_consts, n_params, data, n_cols, n_obs, prior_code, prior_consts, init, proposal_sd, n_iter, seed, backend)

# nolint end
