# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gpumetropolis, .registration = TRUE
NULL

#' Evaluate the batched Gaussian-mean log-density kernel.
#'
#' Internal helper that exposes the compute kernel in isolation so it can be
#' checked directly. `candidates` holds one mean proposal per chain; the return
#' value holds one log-density per chain.
#' @noRd
rust_log_density_batch <- function(candidates, data, sigma) .Call(wrap__rust_log_density_batch, candidates, data, sigma)

#' Run the batched random-walk Metropolis sampler (CPU reference).
#'
#' Internal worker behind the R function `metropolis_gaussian_mean()`. Returns
#' a list with the `n_iter` by `n_chains` matrix of draws and the per-chain
#' acceptance rate.
#' @noRd
rust_metropolis_gaussian_mean <- function(data, sigma, n_iter, init, proposal_sd, seed) .Call(wrap__rust_metropolis_gaussian_mean, data, sigma, n_iter, init, proposal_sd, seed)

# nolint end
