# Generated by extendr: Do not edit by hand
# nolint start

#' @usage NULL
#' @useDynLib gpumetropolis, .registration = TRUE
NULL

#' Evaluate the batched Gaussian-mean log-density kernel.
#'
#' Internal helper behind the Phase 0 reference sampler.
#' @noRd
rust_log_density_batch <- function(candidates, data, sigma) .Call(wrap__rust_log_density_batch, candidates, data, sigma)

#' Run the batched random-walk Metropolis sampler (CPU reference).
#'
#' Internal worker behind the R function `metropolis_gaussian_mean()`.
#' @noRd
rust_metropolis_gaussian_mean <- function(data, sigma, n_iter, init, proposal_sd, seed) .Call(wrap__rust_metropolis_gaussian_mean, data, sigma, n_iter, init, proposal_sd, seed)

#' Names of the compute backends compiled into this build.
#'
#' Always includes "cpu"; "cuda" and "vulkan" are present only when the
#' matching Cargo feature was enabled at build time.
#' @noRd
rust_available_backends <- function() .Call(wrap__rust_available_backends)

#' Run the generic batched Metropolis sampler over a compiled model.
#'
#' Internal worker behind `gpu_metropolis()`. The log-density is given as
#' compiled bytecode; `draws` is returned flat in the column-major order of an
#' R array of dimension (n_iter, n_chains, n_params).
#' @noRd
rust_gpu_metropolis <- function(loglik_code, loglik_consts, n_params, data, n_cols, n_obs, prior_code, prior_consts, init, proposal_sd, n_iter, seed, backend) .Call(wrap__rust_gpu_metropolis, loglik_code, loglik_consts, n_params, data, n_cols, n_obs, prior_code, prior_consts, init, proposal_sd, n_iter, seed, backend)

# nolint end
